[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
    let g:NERDSpaceDelims = 1
    nmap <Space>c <Plug>NERDCommenterToggle
    vmap <Space>c <Plug>NERDCommenterToggle
'''

# [[plugins]]
# repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'kana/vim-altr'
hook_add = '''
    nmap <Space>a <Plug>(altr-forward)
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-quickrun'
# on_map = '<Plug>'
hook_add = '''
    source ~/.vim/rc/plugins/quickrun.vim
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
# depends = 'vim-quickrun'

# [[plugins]]
# repo = 'osyo-manga/vim-watchdogs'
# depends = [
  # 'vim-hier',
  # 'quickfixstatus',
  # 'shabadou.vim',
  # 'vim-quickrun',
# ]
#hook_add = '''
    #let g:watchdogs_check_BufWritePost_enable = 1
    #let g:watchdogs_check_CursorHold_enable = 1
#'''

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
    set statusline+=%#warningmsg#
    set statusline+=%{SyntasticStatuslineFlag()}
    set statusline+=%*
    let g:syntastic_always_populate_loc_list = 1
    let g:syntastic_auto_loc_list = 1
    let g:syntastic_check_on_open = 1
    let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'jceb/vim-hier'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
                \ 'colorscheme': 'solarized'
                \ }
'''

[[plugins]]
repo = 'tpope/vim-dispatch'


# [[plugins]]
# repo = 'cocopon/vaffle.vim'
# hook_add = '''
    # source ~/.vim/rc/plugins/vaffle.vim
# '''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

##############################
# Unite/Denite
##############################

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source ~/.vim/rc/plugins/denite.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'tsukkee/unite-tag'

##############################
# Git
##############################

[[plugins]]
repo = 'tpope/vim-fugitive'

##############################
# Colorscheme
##############################

[[plugins]]
repo = 'altercation/vim-colors-solarized'

##############################
# Gradle
##############################

[[plugins]]
repo = 'tfnico/vim-gradle'

##############################
# Graphviz, PlantUML
##############################

[[plugins]]
repo = 'wannesm/wmgraphviz.vim'
hook_add = '''
    let g:WMGraphviz_output = 'png'
'''

[[plugins]]
repo = 'aklt/plantuml-syntax'
