version: '2'
services:
    dev:
        build:
            context: .
            args:
                - http_proxy=${http_proxy}
                - https_proxy=${https_proxy}
        ports:
            - "3000:3000"
            - "5000:5000"
            - "8080:8080"
